/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;

/**
 *
 * @author dam2_alu10@inf.ald
 */
public class LoginRegisterJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginRegisterJDialog
     */
    public LoginRegisterJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStylesButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRegisterJLabel = new javax.swing.JLabel();
        registerJLabel = new javax.swing.JLabel();
        userJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        confirmedPasswordJLabel = new javax.swing.JLabel();
        userJTextField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        confirmedPasswordJTextField = new javax.swing.JPasswordField();
        passwordJTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginRegisterJLabel.setText("Login");

        registerJLabel.setText("Register");

        userJLabel.setText("User:");

        passwordJLabel.setText("Password:");

        confirmedPasswordJLabel.setText("Confirmed:");

        loginJButton.setText("Login");

        registerJButton.setText("Register");

        cancelJButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginJButton)
                                .addGap(18, 18, 18)
                                .addComponent(registerJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(loginRegisterJLabel)
                                .addGap(37, 37, 37)
                                .addComponent(registerJLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordJLabel)
                            .addComponent(confirmedPasswordJLabel)
                            .addComponent(userJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmedPasswordJTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userJTextField)
                                    .addComponent(passwordJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginRegisterJLabel)
                    .addComponent(registerJLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userJLabel)
                    .addComponent(userJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmedPasswordJLabel)
                    .addComponent(confirmedPasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(registerJButton)
                    .addComponent(cancelJButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }

    public void cancelJButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void registerJButtonActionListener(ActionListener al) {
        this.registerJButton.addActionListener(al);
    }

    public void setVisibleRegisterJButton(Boolean enable) {
        this.registerJButton.setVisible(enable);
    }

    public void setVisibleLoginJButton(Boolean enable) {
        this.loginJButton.setVisible(enable);
    }

    public void setVisibleLabelLogin(Boolean enable) {
        this.loginRegisterJLabel.setVisible(enable);
    }

    public void setVisibleLableRegister(Boolean enable) {
        this.registerJLabel.setVisible(enable);
    }

    public void setVisibleLabelConfirmedPassword(Boolean enable) {
        this.confirmedPasswordJLabel.setVisible(enable);
    }

    public void setVisilePasswordJTextField(Boolean enable) {
        this.confirmedPasswordJTextField.setVisible(enable);
    }
    
    public String getUserNameTextFiel(){
        return this.userJTextField.getText();
    }
    
    public String getPasswordTextField(){
        return new String(this.passwordJTextField.getPassword());
    }
   
    public String getConfirmedPasswordTextField(){
       return new String(this.confirmedPasswordJTextField.getPassword());
    }
    
    private void applyStylesButton() {
        cancelJButton.setBackground(new Color(231, 76, 60));
        cancelJButton.setForeground(Color.WHITE);
        cancelJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        loginJButton.setBackground(new Color(46, 204, 113));
        loginJButton.setForeground(Color.WHITE);
        loginJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        loginJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        registerJButton.setBackground(new Color(46, 204, 113));
        registerJButton.setForeground(Color.WHITE);
        registerJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        registerJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        cancelJButton.setFocusPainted(false);
        loginJButton.setFocusPainted(false);
        registerJButton.setFocusPainted(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel confirmedPasswordJLabel;
    private javax.swing.JPasswordField confirmedPasswordJTextField;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginRegisterJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJTextField;
    private javax.swing.JButton registerJButton;
    private javax.swing.JLabel registerJLabel;
    private javax.swing.JLabel userJLabel;
    private javax.swing.JTextField userJTextField;
    // End of variables declaration//GEN-END:variables
}
