/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.image.RenderedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author nerea
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        applyStylesButton();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJLabel = new javax.swing.JLabel();
        characterJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        searchJButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        moviesJScrollPane = new javax.swing.JScrollPane();
        listFilmsTextArea = new javax.swing.JTextArea();
        imageCharacterLabel = new javax.swing.JLabel();
        addFilmsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 204, 255));
        setForeground(new java.awt.Color(102, 153, 255));
        setMaximumSize(new java.awt.Dimension(552, 358));

        imageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");

        registerJButton.setText("Register");

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        nameLabel.setPreferredSize(new java.awt.Dimension(200, 20));

        listFilmsTextArea.setColumns(20);
        listFilmsTextArea.setRows(5);
        moviesJScrollPane.setViewportView(listFilmsTextArea);

        imageCharacterLabel.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(characterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(searchJButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginJButton)
                                .addGap(74, 74, 74)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(registerJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cancelJButton)
                                .addGap(18, 18, 18)
                                .addComponent(addJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addFilmsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageCharacterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moviesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJButton)
                    .addComponent(cancelJButton)
                    .addComponent(addJButton)
                    .addComponent(addFilmsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageCharacterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moviesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(registerJButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addJButtonActionPerformed

    public void setTamanhoImage(int width, int height) {
        imageJLabel.setSize(width, height);
    }

    public void setTamanhoImageCharacter(int width, int height) {
        imageCharacterLabel.setSize(width, height);
    }

    public void getImagetoLabel(ImageIcon image) {
        int width = imageJLabel.getWidth();
        int height = imageJLabel.getHeight();

        Image newImage = image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        imageJLabel.setIcon(new ImageIcon(newImage));

    }

    public String getCharacterJTextField() {
        return characterJTextField.getText().trim();
    }

    public void setNameLabel(String name) {
        this.nameLabel.setText(name);
    }

    public void setCharacterJTextField(String character) {
        this.characterJTextField.setText(character);
    }

    public void addSearchJButtonActionListener(ActionListener al) {
        this.searchJButton.addActionListener(al);
    }

    public void addJButtonActionListener(ActionListener al) {
        this.addJButton.addActionListener(al);
    }

    public void setEnableAddJButton(Boolean enable) {
        this.addFilmsTextField.setEnabled(enable);
    }

    public void setEnableMoviesJTextField(Boolean enable) {
        this.addFilmsTextField.setEnabled(enable);
    }

    public void addCancelJButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void addLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }

    public void addRegisterJButtonActionListener(ActionListener al) {
        this.registerJButton.addActionListener(al);
    }

    public void setImageCharacterLabel(int width, int height) {
        imageCharacterLabel.setSize(width, height);
    }

    public void getImageCharacterLabel(ImageIcon image) {
        int width = imageCharacterLabel.getWidth();
        int height = imageCharacterLabel.getHeight();

        Image newImage = image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        imageCharacterLabel.setIcon(new ImageIcon(newImage));

    }

    public void setVisibleLabelImage(Boolean enable) {
        this.imageCharacterLabel.setVisible(enable);
    }

    public void setVisibleTextAreal(Boolean enable) {
        this.moviesJScrollPane.setVisible(enable);
        this.listFilmsTextArea.setVisible(enable);
        this.listFilmsTextArea.revalidate();
        this.listFilmsTextArea.repaint();
    }

    public void setListFilmsTextArea(List<String> films) {
        this.listFilmsTextArea.setText("");

        if (films != null && !films.isEmpty()) {
            for (int i = 0; i < films.size(); i++) {
                String film = films.get(i);
                this.listFilmsTextArea.append(film + "\n");
            }
        } else {
            this.listFilmsTextArea.setText("No hay películas disponibles");
        }
    }

    public void setVisibleNameLabel(boolean enable) {
        this.nameLabel.setVisible(enable);
    }

    public void setFilmsTextField(String films) {
        this.addFilmsTextField.setText(films);
    }

    public String getFilmsTextField() {
        return this.addFilmsTextField.getText();
    }

    private void applyStylesButton() {

        //Estilos para el botón buscaar
        searchJButton.setBackground(new Color(52, 152, 219));
        searchJButton.setForeground(Color.WHITE);
        searchJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        searchJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        //Estilos para el boton cancelar
        cancelJButton.setBackground(new Color(231, 76, 60));
        cancelJButton.setForeground(Color.WHITE);
        cancelJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        cancelJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        //Estilos para el boton añadir
        addJButton.setBackground(new Color(46, 204, 113));
        addJButton.setForeground(Color.WHITE);
        addJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        addJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        //Estilos para el botón login
        loginJButton.setBackground(new Color(155, 89, 182));
        loginJButton.setForeground(Color.WHITE);
        loginJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        loginJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        //Estilos boton register
        registerJButton.setBackground(new Color(230, 126, 34));
        registerJButton.setForeground(Color.WHITE);
        registerJButton.setFont(new Font("Segoe UI", Font.BOLD, 12));
        registerJButton.setBorder(BorderFactory.createEmptyBorder(8, 15, 8, 15));

        // Quitar borde de los botones
        searchJButton.setFocusPainted(false);
        cancelJButton.setFocusPainted(false);
        addJButton.setFocusPainted(false);
        loginJButton.setFocusPainted(false);
        registerJButton.setFocusPainted(false);

        //Cambiar el cursor al pasar por delante de los botones
        searchJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cancelJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        loginJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        registerJButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addFilmsTextField;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField characterJTextField;
    private javax.swing.JLabel imageCharacterLabel;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JTextArea listFilmsTextArea;
    private javax.swing.JButton loginJButton;
    private javax.swing.JScrollPane moviesJScrollPane;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton registerJButton;
    private javax.swing.JButton searchJButton;
    // End of variables declaration//GEN-END:variables
}
