/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu10@inf.ald
 */
public class LoginRegisterJDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginRegisterJDialog
     */
    public LoginRegisterJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginRegisterJLabel = new javax.swing.JLabel();
        registerJLabel = new javax.swing.JLabel();
        userJLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        confirmedPasswordJLabel = new javax.swing.JLabel();
        userJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        confirmedPasswordJTextField = new javax.swing.JTextField();
        loginJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        loginRegisterJLabel.setText("Login");

        registerJLabel.setText("Register");

        userJLabel.setText("User");

        passwordJLabel.setText("Password");

        confirmedPasswordJLabel.setText("Confirmed");

        loginJButton.setText("Login");

        registerJButton.setText("Register");

        cancelJButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmedPasswordJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(confirmedPasswordJTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(passwordJLabel)
                        .addGap(23, 23, 23)
                        .addComponent(passwordJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginJButton)
                                .addGap(18, 18, 18)
                                .addComponent(registerJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userJLabel)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(loginRegisterJLabel)
                                        .addGap(37, 37, 37)
                                        .addComponent(registerJLabel))
                                    .addComponent(userJTextField))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginRegisterJLabel)
                    .addComponent(registerJLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userJLabel)
                    .addComponent(userJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmedPasswordJLabel)
                    .addComponent(confirmedPasswordJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(registerJButton)
                    .addComponent(cancelJButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getConfirmedPasswordJTextField() {
        return confirmedPasswordJTextField.getText();
    }

    public void setConfirmedPasswordJTextField(String confirmedPass) {
        this.confirmedPasswordJTextField.setText(confirmedPass);
    }

    public String getPasswordJTextField() {
        return passwordJTextField.getText();
    }

    public void setPasswordJTextField(String password) {
        this.passwordJTextField.setText(password);
    }

    public String getUserJTextField() {
        return userJTextField.getText();
    }

    public void setUserJTextField(String user) {
        this.userJTextField.setText(user);
    }
    
    public void loginJButtonActionListener(ActionListener al){
        this.loginJButton.addActionListener(al);
    }
    public void cancelJButtonActionListener(ActionListener al){
        this.cancelJButton.addActionListener(al);
    }
    public void registerJButtonActionListener(ActionListener al){
        this.registerJButton.addActionListener(al);
    }
    public void setVisibleRegisterJButton(Boolean enable){
        this.registerJButton.setVisible(enable);
    }
    public void setVisibleLoginJButton(Boolean enable){
        this.loginJButton.setVisible(enable);
    }
    public void setVisibleLabelLogin(Boolean enable){
        this.loginRegisterJLabel.setVisible(enable);
    }
    public void setVisibleLableRegister(Boolean enable){
        this.registerJLabel.setVisible(enable);
    }
    public void setVisibleLabelConfirmedPassword(Boolean enable){
        this.confirmedPasswordJLabel.setVisible(enable);
    }
    public void setVisilePasswordJTextField(Boolean enable){
        this.confirmedPasswordJTextField.setVisible(enable);
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel confirmedPasswordJLabel;
    private javax.swing.JTextField confirmedPasswordJTextField;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginRegisterJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JButton registerJButton;
    private javax.swing.JLabel registerJLabel;
    private javax.swing.JLabel userJLabel;
    private javax.swing.JTextField userJTextField;
    // End of variables declaration//GEN-END:variables
}
