/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author nerea
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJLabel = new javax.swing.JLabel();
        characterJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        registerJButton = new javax.swing.JButton();
        searchJButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFilmsTextArea = new javax.swing.JTextArea();
        imageCharacterJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 204, 255));
        setForeground(new java.awt.Color(102, 153, 255));
        setMaximumSize(new java.awt.Dimension(552, 358));

        imageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setText("Cancel");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");

        registerJButton.setText("Register");

        searchJButton.setText("Search");
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        nameLabel.setPreferredSize(new java.awt.Dimension(200, 20));

        listFilmsTextArea.setColumns(20);
        listFilmsTextArea.setRows(5);
        jScrollPane2.setViewportView(listFilmsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginJButton)
                            .addComponent(characterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerJButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchJButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelJButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(addJButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageCharacterJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelJButton)
                    .addComponent(searchJButton)
                    .addComponent(addJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(imageCharacterJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(registerJButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addJButtonActionPerformed

    public void setTamanhoImage(int width, int height) {
        imageJLabel.setSize(width, height);
    }

    public void getImagetoLabel(ImageIcon image) {
        int width = imageJLabel.getWidth();
        int height = imageJLabel.getHeight();

        Image newImage = image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        imageJLabel.setIcon(new ImageIcon(newImage));

    }

    public String getCharacterJTextField() {
        return characterJTextField.getText().trim();
    }

    public void setNameLabel(String name) {
        this.nameLabel.setText(name);
    }

    public void setCharacterJTextField(String character) {
        this.characterJTextField.setText(character);
    }

    public void setImagePanel(String imageUrl) {
        try {

            ImageIcon icon = new ImageIcon(new java.net.URL(imageUrl));

            Image img = icon.getImage().getScaledInstance(
                    imagePanel.getWidth(), 
                    imagePanel.getHeight(), 
                    Image.SCALE_SMOOTH
            );
            icon = new ImageIcon(img);

            imagePanel.removeAll();

            JLabel imgLabel = new JLabel(icon);
            imagePanel.add(imgLabel);

            imagePanel.revalidate();
            imagePanel.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error loading image: " + imageUrl);
        }
    }
    
    public void addSearchJButtonActionListener(ActionListener al) {
        this.searchJButton.addActionListener(al);
    }

    public void addJButtonActionListener(ActionListener al) {
        this.addJButton.addActionListener(al);
    }

    public void addCancelJButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void addLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }

    public void addRegisterJButtonActionListener(ActionListener al) {
        this.registerJButton.addActionListener(al);
    }
    
    public void setImageCharacter(String url){
        this.imageCharacterJLabel.setText(url);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JTextField characterJTextField;
    private javax.swing.JLabel imageCharacterJLabel;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea listFilmsTextArea;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton registerJButton;
    private javax.swing.JButton searchJButton;
    // End of variables declaration//GEN-END:variables
}
